In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\sivap\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\sivap\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sivap\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\sivap\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\sivap\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [13]:

data = {"Name": ["Alice","Bob"],"Age": [25, 30]}
df = pd.DataFrame(data)
df

    Name  Age
0  Alice   25
1    Bob   30

In [14]:
lst = [["Alice", 25], ["Bob", 30]]
df = pd.DataFrame(lst,columns=["Name","Age"])
df

    Name  Age
0  Alice   25
1    Bob   30

In [8]:
df.head() 
df.tail() 
df.info() 
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [16]:
df["Name"]
df[["Name","Age"]]

    Name  Age
0  Alice   25
1    Bob   30

In [15]:
df.loc[0]
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [17]:
df[df["Age"] > 25]

  Name  Age
1  Bob   30

In [22]:
df["Gender"] = ["F","M"]
print(df.columns)
df.drop("Age", axis=1, inplace=True,errors="ignore") 
df

Index(['Name', 'Gender'], dtype='str')

    Name Gender
0  Alice      F
1    Bob      M

In [23]:
df.isnull()
df.dropna()
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [26]:
df=pd.DataFrame({"Name":["Alice","Bob"],"Age":[25,30],"Gender":["F","M"]})
df.groupby("Gender")["Age"].mean()

Gender
F    25.0
M    30.0
Name: Age, dtype: float64

In [34]:
df1 = pd.DataFrame({"key":[1,2],"Name":["Alice","Bob"]})
df2=pd.DataFrame({"key":[1,2,3],"Age":[25,30,35]})
pd.merge(df1, df2, on="key")
df1.join(df2,lsuffix="_left",rsuffix="_right")

   key_left   Name  key_right  Age
0         1  Alice          1   25
1         2    Bob          2   30

In [16]:
df.to_csv("data.csv",index=False)

In [17]:
df=pd.read_csv("data.csv")
print(df)

    Name  Age
0  Alice   25
1    bob   30

In [19]:
df.sort_values("Age")
df["Age"].apply(lambda x: x + 1)
df["Name"].unique()
df["Age"].value_counts()

Age
25    1
30    1
Name: count, dtype: int64